kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.redis.persistence.name }}
  labels:
    app: web
spec:
  capacity:
    storage: {{.Values.redis.persistence.size}}
  volumeMode: Filesystem
  accessModes:
  - {{ .Values.redis.persistence.access_mode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.redis.persistence.storage_class }}
  nfs:
    {{- toYaml .Values.redis.persistence.nfs | nindent 4 }}
