{{- if .Values.elasticsearch.secret.data -}}
apiVersion: v1
data:
  {{- toYaml .Values.elasticsearch.secret.data | nindent 2 }}
kind: Secret
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-secret
type: Opaque
{{- end -}}

